/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPackagingRouteImport } from './routes/_authenticated/packaging'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedCustomersIdRouteImport } from './routes/_authenticated/customers.$id'
import { Route as AuthenticatedPackagingIdRouteImport } from './routes/_authenticated/packaging.$id'
import { Route as AuthenticatedProductsIdRouteImport } from './routes/_authenticated/products.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPackagingRoute = AuthenticatedPackagingRouteImport.update({
  id: '/packaging',
  path: '/packaging',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersIdRoute =
  AuthenticatedCustomersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCustomersRoute,
  } as any)
const AuthenticatedPackagingIdRoute =
  AuthenticatedPackagingIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPackagingRoute,
  } as any)
const AuthenticatedProductsIdRoute = AuthenticatedProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/packaging': typeof AuthenticatedPackagingRouteWithChildren
  '/products': typeof AuthenticatedProductsRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/packaging/$id': typeof AuthenticatedPackagingIdRoute
  '/products/$id': typeof AuthenticatedProductsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/packaging': typeof AuthenticatedPackagingRouteWithChildren
  '/products': typeof AuthenticatedProductsRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/packaging/$id': typeof AuthenticatedPackagingIdRoute
  '/products/$id': typeof AuthenticatedProductsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/packaging': typeof AuthenticatedPackagingRouteWithChildren
  '/_authenticated/products': typeof AuthenticatedProductsRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/_authenticated/packaging/$id': typeof AuthenticatedPackagingIdRoute
  '/_authenticated/products/$id': typeof AuthenticatedProductsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/login'
    | '/approvals'
    | '/audit'
    | '/customers'
    | '/dashboard'
    | '/packaging'
    | '/products'
    | '/users'
    | '/customers/$id'
    | '/packaging/$id'
    | '/products/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/login'
    | '/approvals'
    | '/audit'
    | '/customers'
    | '/dashboard'
    | '/packaging'
    | '/products'
    | '/users'
    | '/customers/$id'
    | '/packaging/$id'
    | '/products/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/login'
    | '/_authenticated/approvals'
    | '/_authenticated/audit'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/packaging'
    | '/_authenticated/products'
    | '/_authenticated/users'
    | '/_authenticated/customers/$id'
    | '/_authenticated/packaging/$id'
    | '/_authenticated/products/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/packaging': {
      id: '/_authenticated/packaging'
      path: '/packaging'
      fullPath: '/packaging'
      preLoaderRoute: typeof AuthenticatedPackagingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/$id': {
      id: '/_authenticated/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AuthenticatedCustomersIdRouteImport
      parentRoute: typeof AuthenticatedCustomersRoute
    }
    '/_authenticated/packaging/$id': {
      id: '/_authenticated/packaging/$id'
      path: '/$id'
      fullPath: '/packaging/$id'
      preLoaderRoute: typeof AuthenticatedPackagingIdRouteImport
      parentRoute: typeof AuthenticatedPackagingRoute
    }
    '/_authenticated/products/$id': {
      id: '/_authenticated/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AuthenticatedProductsIdRouteImport
      parentRoute: typeof AuthenticatedProductsRoute
    }
  }
}

interface AuthenticatedCustomersRouteChildren {
  AuthenticatedCustomersIdRoute: typeof AuthenticatedCustomersIdRoute
}

const AuthenticatedCustomersRouteChildren: AuthenticatedCustomersRouteChildren =
  {
    AuthenticatedCustomersIdRoute: AuthenticatedCustomersIdRoute,
  }

const AuthenticatedCustomersRouteWithChildren =
  AuthenticatedCustomersRoute._addFileChildren(
    AuthenticatedCustomersRouteChildren,
  )

interface AuthenticatedPackagingRouteChildren {
  AuthenticatedPackagingIdRoute: typeof AuthenticatedPackagingIdRoute
}

const AuthenticatedPackagingRouteChildren: AuthenticatedPackagingRouteChildren =
  {
    AuthenticatedPackagingIdRoute: AuthenticatedPackagingIdRoute,
  }

const AuthenticatedPackagingRouteWithChildren =
  AuthenticatedPackagingRoute._addFileChildren(
    AuthenticatedPackagingRouteChildren,
  )

interface AuthenticatedProductsRouteChildren {
  AuthenticatedProductsIdRoute: typeof AuthenticatedProductsIdRoute
}

const AuthenticatedProductsRouteChildren: AuthenticatedProductsRouteChildren = {
  AuthenticatedProductsIdRoute: AuthenticatedProductsIdRoute,
}

const AuthenticatedProductsRouteWithChildren =
  AuthenticatedProductsRoute._addFileChildren(
    AuthenticatedProductsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPackagingRoute: typeof AuthenticatedPackagingRouteWithChildren
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRouteWithChildren
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPackagingRoute: AuthenticatedPackagingRouteWithChildren,
  AuthenticatedProductsRoute: AuthenticatedProductsRouteWithChildren,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
